yatube/about/urls.py
from django.urls import path

from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('create/', views.post_create, name='create'),
    path('posts/<post_id>/edit/', views.post_edit, name='edit'),
    path('posts/<post_id>/delete/', views.post_delete, name='delete'),
    path('posts/<int:post_id>/comment/',
         views.add_comments, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path('profile/<str:username>/follow/',
         views.profile_follow, name='profile_follow'),
    path('profile/<str:username>/unfollow/',
         views.profile_unfollow, name='profile_unfollow'),
    path('posts/<int:posts>/like',
         views.post_like, name='like'),
    path('posts/<int:posts>/unlike',
         views.post_unlike, name='unlike')
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.internal_server_error'
handler403 = 'core.views.csrf_failure'

urlpatterns = [
    path('admin/', admin.site.urls,),
    path('', include('posts.urls')),
    path('auth/', include('users.urls')),
    path('about/', include('about.urls'))
]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Post(models.Model):
    text = models.TextField(verbose_name='Текст поста')
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор поста'
    )
    group = models.ForeignKey(
        'Group',
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа'
    )
    image = models.ImageField(
        verbose_name='Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Group(models.Model):
    title = models.CharField(verbose_name='Название группы', max_length=200)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField(verbose_name='Описание группы')

    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'

    def __str__(self):
        return self.title


class Comment(models.Model):
    text = models.TextField(verbose_name='Текст комментария')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )
    created = models.DateTimeField(auto_now_add=True,
                                   verbose_name='Время публикации комментария')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['-created']

    def __str__(self):
        return self.text[:30]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
        verbose_name='Пользователь'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

    def __str__(self):
        return (f'Пользователь {self.user} '
                f'подписался на {self.author}')


class Like(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='post_like',
        verbose_name='Пост',
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='user_like',
        verbose_name='Пользователь'
    )
    like = models.BooleanField(default=False,
                               verbose_name='like')

    def __str__(self):
        return(f'Пользователь {self.user} '
               f'лайкнул {self.post.text}')

yatube/posts/forms.py
from django.forms import ModelForm

from .models import Post, Comment


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['text', 'group', 'image']


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.core.cache import cache

from .models import Post, Group, User, Follow, Like
from .forms import PostForm, CommentForm

MY_SLICE = 10
CACHE_TIME = 20


def index(request):
    templates = 'posts/index.html'
    posts = cache.get('posts')
    if not posts:
        posts = Post.objects.all().select_related()
        cache.set('posts', posts, CACHE_TIME)
    paginator = Paginator(posts, MY_SLICE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'title': 'Это главная страница проекта Yatube',
        'page_obj': page_obj,
    }
    return render(request, templates, context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    title = group.title
    templates = 'posts/group_list.html'
    paginator = Paginator(posts, MY_SLICE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'group': group,
        'title': title,
        'page_obj': page_obj,

    }
    return render(request, templates, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    all_posts_count = post.author.posts.count()
    context = {
        'post': post,
        'all_posts': all_posts_count,
        'form': CommentForm(request.POST or None),
        'comments': post.comments.all()

    }
    return render(request, 'posts/post_detail.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)

    post_list = Post.objects.filter(author__username=username).all()
    paginator = Paginator(post_list, MY_SLICE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    following_flag = False
    if ((request.user.is_authenticated)
            and Follow.objects.filter(
                user=request.user, author=author).exists()):
        following_flag = True

    context = {
        'author': author,
        'post_count': len(post_list),
        'page_obj': page_obj,
        'following': following_flag
    }
    return render(request, 'posts/profile.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST)
    if form.is_valid():
        new_post = form.save(commit=False)
        new_post.author = request.user
        new_post.save()
        return redirect('posts:profile', new_post.author)

    form = PostForm()

    context = {
        'form': form,
        'is_edit': False
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'is_edit': True,
        'post': post,
        'form': form,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)
    post.delete()
    return redirect('posts:profile', username=request.user)


@login_required
def add_comments(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
        return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts_list = Post.objects.filter(author__following__user=request.user)
    paginator = Paginator(posts_list, MY_SLICE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    template = 'posts/follow.html'
    context = {
        'page_obj': page,
        'title': 'Избранные авторы'
    }
    return render(request, template, context)


@login_required
def profile_follow(request, username):
    profile_user = get_object_or_404(User, username=username)
    if request.user != profile_user:
        Follow.objects.get_or_create(user=request.user, author=profile_user)
        return redirect('posts:profile', username=username)
    return redirect('posts:main')


@login_required
def profile_unfollow(request, username):
    profile_user = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=profile_user).delete()
    return redirect('posts:profile', username=username)

@login_required
def post_like(request, posts):
    post = get_object_or_404(Post, pk=posts)
    Like.objects.create(
        post=post,
        user=request.user,
        like=True
    )
    return redirect('posts:main')


@login_required
def post_unlike(request, posts):
    post = get_object_or_404(Post, pk=posts)
    Like.objects.filter(
        post=post,
        user=request.user,
        like=True
    ).delete()
    return redirect('posts:main')

yatube/templates/posts/comment.html
{% load user_filters %}

{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}
        <div class="form-group mb-2">
          {{ form.text|addclass:"form-control" }}
        </div>
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}

{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
      <p>
        {{ comment.text }}
      </p>
    </div>
  </div>
{% endfor %}

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}
{%block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          {% if is_edit %}
            Редактировать пост
          {% else %}
            Новый пост
          {% endif %}
        </div>
        <div class="card-body">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="id_text">
                  <label for="{{ field.id_for_label }}">
                    {{ field.label }}
                    {% if field.field.required %}
                      <span class="required text-danger">*</span>
                    {% endif %}
                  </label>
                  {{ field|addclass:'form-control' }}
                  {% if field.help_text %}
                    {{ field.help_text }}
                  {% endif %}
                </div>
            {% endfor %}
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">
                {% if is_edit %}
                  Редактировать
                {% else %}
                  Добавить
                {% endif %}
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
  </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Избранные авторы
{% endblock %}
{% block content%}
{% include 'includes/switcher.html' %}
  <h3> {{title}} </h3>
  <ul>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    <p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
    </p>
    {% if post.group %}
      <a href="{% url 'posts:group' post.group.slug %}">Перейти в группу {{ post.group.title }}</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  </ul>

{%endblock%}

yatube/templates/posts/group_list.html
{%extends 'base.html'%}
{% load thumbnail %}
{%block title%}
  Группа: {{title}}
{%endblock%}
{% block header %}<h1>{{group.title}}</h1>{% endblock %}
{%block content%}
  <p>
    {{group.description}}
  </p>

  {% for post in page_obj %}
    <arcticle>
      <ul>
        <li>
          Автор: {{post.author.get_full_name}}
        </li>
        <li>
          Дата публикации: {{post.pub_date|date:"d E Y"}}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
      <p>
        {{post.text}}
      </p>
      <p>
        <a href="{% url 'posts:post_detail' post.id %}">Прочитать статью целиком.</a>
      </p>
    </arcticle>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}
  Главная страница
{% endblock %}
{% block content%}
{% include 'includes/switcher.html' %}
  <h3> {{title}} </h3>
  <ul>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author.get_full_name }}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    <p>{{ post.text }}</p>
    <p>
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
    </p>
    {% if post.group %}
      <a href="{% url 'posts:group' post.group.slug %}">Перейти в группу {{ post.group.title }}</a>
        <a href="{% url 'posts:like' post.id %}">Лайк</a>
        <a href="{% url 'posts:unlike' post.id %}">Не лайк</a>
    {% endif %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  </ul>

{%endblock%}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% block title %} {{ post.text|truncatechars:30}} {% endblock %}
{% load thumbnail %}
{% block content %}
  <body>
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y"  }}
            </li>
            {% if post.group %}
              <li class="list-group-item">
                Группа: {{ post.group.title }}
                <a href="{% url 'posts:group' post.group.slug %}">
                  все записи группы
                </a>
              </li>
            {% endif %}
            <li class="list-group-item">
              Автор: {{ post.author }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  {{ all_posts }}
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post.author %}">
                все посты пользователя
              </a>
              {% if post.author == user %}
                <a type="button" class="btn btn-primary" href="{% url 'posts:edit' post.id %}">Редактиравать запись</a>
                <a type="button" class="btn btn-danger" href="{% url 'posts:delete' post.id %}">Удалить запись</a>
              {% endif %}
            </li>
          </ul>
        </aside>

        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
            {{ post.text }}
          </p>
          {% include 'posts/comment.html'%}
        </article>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
  {% block title %}Профайл пользователя {{ author.get_full_name }} {% endblock%}
  {% block content %}
    <main>
      <div class="mb-5">
  <h1>Все посты пользователя {{ author.get_full_name }}</h1>
  <h3>Всего постов: {{ post_count }}</h3>
  <h4> Подписки: {{ author.follower.count }}</h4>
          <h4>Подписчики: {{ author.following.count }} </h4>
  {% if author != request.user %}
    {% if following %}
        <a
        class="btn btn-lg btn btn-danger"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
            >
        Отписаться
     </a>
    {% else %}
        <a
            class="btn btn-lg btn btn-primary"
            href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
            Подписаться
        </a>
    {% endif %}
  {% endif %}
</div>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' author %}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y"}}
            </li>
          </ul>
          {% thumbnail post.image "1920x1080" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>
          {{ post.text }}
          </p>
        <li>
          <a href="{% url 'posts:post_detail' post.id %}">подробная информация </a>
        {% if post.group %}
          <li>
        <a href="{% url 'posts:group' post.group.slug %}">все записи группы</a>
      </li>
        {% endif %}
        <hr>
        {% endfor %}
      </div>
    </main>
  {% endblock %}